---
- name: Create application on Ravello
  connection: local
  hosts: all
  gather_facts: no
  roles:
    - ravello.lib
    - ravello.application_create
  vars:
    ansible_python_interpreter: /usr/local/bin/python
  pre_tasks:
    - include_vars: "{{ topology_file }}"
