---
- name: Manage Application on Ravello
  connection: local
  hosts: all,pfe
  gather_facts: no
  roles:
    - ravello.lib
    - ravello.application_create
    - ravello.vm_start
    - ravello.get_fqdn
    - ravello.application_delete
  pre_tasks:
    - include_vars: "{{ topology_file }}"
